name: issue-workflow
on: issues
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning Repo
        uses: actions/checkout@v3
      - name: Output event details
        run: echo ${{toJSON(github)}}
